<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventorySystem.Common\InventorySystem.Common.csproj" />
    <ProjectReference Include="..\InventorySystem.Data\InventorySystem.Data.csproj" />
    <ProjectReference Include="..\InventorySystem.Model\InventorySystem.Model.csproj" />
  </ItemGroup>

</Project>
